---
- name: Install config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    force: "{{ item.force }}"
  with_items:
    - { src: 'etc_teleport.yaml.j2', dest: '/etc/teleport.yaml', owner: 'root', group: 'root', mode: '0644', force: 'yes' }
  register: tp_configfiles

